### ISSUE TITLE
Не глупи...

### ISSUE THREAD

**Issue by UtopiaBe** [gleb89/fast-api#1]
Дружище...
У тебя в fast-api/config/db.py - все данные подключения к базе...
Не делай так... пользуйся .ENV

Удаляй скорей...

**Comment by gleb89** [comment]
Спасибо ,да это понятно ) ещё не для готовой сборки продакшена

Отправлено с iPhone

**Comment by gleb89** [comment]
Там обычная база тестовая в heroku висит

Отправлено с iPhone

**Comment by gleb89** [comment]
Переделал ,ещё раз спасибо ) я и забыл про это если честно

Отправлено с iPhone

**Comment by UtopiaBe** [comment]
Не за что =) рад помочь

вс, 24 янв. 2021 г. в 10:44, gleb89 <notifications@github.com>:
